version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10

    - package-ecosystem: 'npm'
      directory: '/generators/svelte/dependabot/svelte'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      versioning-strategy: increase

    - package-ecosystem: 'npm'
      directory: '/generators/svelte/dependabot/swagger/'
      schedule:
          interval: 'daily'
      open-pull-requests-limit: 10
      versioning-strategy: increase
