#!/bin/sh

basedir=`dirname "$0"`

if [ -f "$basedir/mvnw" ]; then
  builddir="target/node"
  installCommand="$basedir/mvnw -ntp frontend:install-node-and-npm@install-node-and-npm"
fi

NPM_EXE="$basedir/$builddir/npm"

if ! [ -x "$NPM_EXE" ]; then
  echo "Using npm installed globally"
  npm "$@"
else
  echo "Using npm installed locally $($NPM_EXE --version)"
  $NPM_EXE "$@"
fi
