name: Publish JHipster Svelte blueprint
on:
    release:
        types: [created]
jobs:
    publish-svelte-blueprint:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
            - name: Checkout JHipster Svelte generator repository
              uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-docker-image:
        needs: publish-svelte-blueprint
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout JHipster Svelte generator repository
              uses: actions/checkout@v4
            - uses: docker/metadata-action@v3
              id: meta
              with:
                  images: jhipster/jhipster-svelte
                  tags: |
                      type=ref,event=tag
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push JHipster Svelte image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile-release
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
